### 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

Lecture Video : https://www.youtube.com/watch?v=V_xro1bcAuA

Created by : `KHIN THANDAR KYAW [29 Apr 2023]`

#### 1. Setting Up

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [3]:
!nvidia-smi

Sat Apr 29 12:32:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

### Creating tensors [multi-dimensional numeric data]

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

![Differences of scalar, vector, matrix, and tensor](https://miro.medium.com/v2/resize:fit:1008/0*zcidDaCCmJeD8y-9.png)

In [4]:
# scalars : no square bracket
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# number of square brackets
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector : 1 square bracket
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# number of sqaure brackets
vector.ndim

1

In [9]:
# as (2x1) in shape (col, row)
# shape = 2
vector.shape

torch.Size([2])

In [10]:
# Matrix : 2 square brackets
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR : 3 square brackets
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

![Explanation of Tensor Dimension](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR[0][1]

tensor([3, 6, 9])

In [20]:
TENSOR[0][0][2]

tensor(3)

### Random tensors

Why random tensors?

Random tensors are important becuase the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [21]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4079, 0.8497, 0.9262, 0.6270],
        [0.5701, 0.9900, 0.2527, 0.0629],
        [0.9025, 0.3303, 0.0949, 0.0875]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([3, 4])

In [24]:
random_tensor_2 = torch.rand(2, 3, 4)
random_tensor_2

tensor([[[0.0323, 0.3147, 0.0481, 0.1269],
         [0.0887, 0.3498, 0.7570, 0.0991],
         [0.2261, 0.6259, 0.0082, 0.2487]],

        [[0.7684, 0.8960, 0.1314, 0.2657],
         [0.5128, 0.0039, 0.6360, 0.1426],
         [0.6787, 0.4299, 0.9389, 0.9549]]])

In [25]:
random_tensor_2.ndim

3

In [26]:
random_tensor_2.shape

torch.Size([2, 3, 4])

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 244)) # color channels(rgb), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 244]), 3)

In [28]:
random_image_size_tensor

tensor([[[0.4581, 0.2142, 0.7122,  ..., 0.0040, 0.0188, 0.8632],
         [0.3489, 0.5822, 0.5023,  ..., 0.6173, 0.7920, 0.1247],
         [0.0448, 0.7205, 0.8442,  ..., 0.5434, 0.1101, 0.3348],
         ...,
         [0.3071, 0.7036, 0.2838,  ..., 0.1943, 0.0119, 0.0696],
         [0.3566, 0.5824, 0.1932,  ..., 0.9114, 0.6566, 0.3630],
         [0.4773, 0.5487, 0.5794,  ..., 0.8999, 0.4659, 0.5196]],

        [[0.7317, 0.6196, 0.6033,  ..., 0.0938, 0.7641, 0.0152],
         [0.2890, 0.4799, 0.9470,  ..., 0.9255, 0.9486, 0.1663],
         [0.7366, 0.6285, 0.0577,  ..., 0.9931, 0.4605, 0.0613],
         ...,
         [0.9246, 0.9450, 0.5323,  ..., 0.9717, 0.5994, 0.8681],
         [0.1272, 0.0596, 0.6372,  ..., 0.5461, 0.9171, 0.9103],
         [0.0574, 0.1618, 0.0998,  ..., 0.1773, 0.5111, 0.6427]],

        [[0.3186, 0.8662, 0.2672,  ..., 0.2364, 0.8686, 0.2915],
         [0.6714, 0.6208, 0.1802,  ..., 0.5815, 0.3226, 0.1497],
         [0.3034, 0.0601, 0.3026,  ..., 0.6832, 0.8858, 0.

In [29]:
torch.rand(size=(3, 3))

tensor([[0.5173, 0.0174, 0.0601],
        [0.9035, 0.8224, 0.3143],
        [0.0630, 0.5511, 0.3473]])

In [30]:
torch.rand(3,3)

tensor([[0.3436, 0.1187, 0.4720],
        [0.2704, 0.5511, 0.3303],
        [0.8462, 0.5164, 0.1880]])

### Zeros and ones

In [31]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros * random_tensor # (3, 4) * (3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype # default datatype = dtype

torch.float32

In [35]:
random_tensor_2.dtype

torch.float32

In [36]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [37]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# creating tensors like
# you do not want to define the shape of a tensor
# instead, you will use the shape of the tensor already created
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing : https://en.wikipedia.org/wiki/Precision_(computer_science)

In [39]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor.dtype

torch.float32

In [41]:
# Float 64 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float64)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [42]:
float_32_tensor.dtype

torch.float64

In [43]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float64)
                               device=None, # what device is your tensor on, gpu : device="cuda"
                               requires_grad=False) # whether or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [44]:
float_32_tensor.dtype

torch.float32

In [45]:
# convert the type of data using the tensor already created
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
float_16_tensor * float_32_tensor # interesting! NO ERROR!

tensor([ 9., 36., 81.])

In [47]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [48]:
float_32_tensor * int_32_tensor # interesting! NO ERROR!

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape    - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [49]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4277, 0.7245, 0.9107, 0.0654],
        [0.5837, 0.2462, 0.9606, 0.4167],
        [0.5156, 0.9858, 0.9820, 0.3991]])

In [50]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [51]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.4277, 0.7245, 0.9107, 0.0654],
        [0.5837, 0.2462, 0.9606, 0.4167],
        [0.5156, 0.9858, 0.9820, 0.3991]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Divsion
* Matrix multiplication

In [52]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
# Addition
tensor + 10

tensor([11, 12, 13])

In [53]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [54]:
tensor.shape

torch.Size([3])

In [55]:
tensor

tensor([1, 2, 3])

In [56]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [57]:
# Try out PyTroch in-built functions

# Multiplication
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [58]:
# Addition
torch.add(tensor, 10)

tensor([11, 12, 13])

In [59]:
# Subtraction
torch.sub(tensor, 10)

tensor([-9, -8, -7])

from ast import Mult
### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html , http://matrixmultiplication.xyz

There are two main rules that performing maultiplication needs to satisfy: 
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work.
* `(2, 3) @ (3, 2)` will work.
* `(3, 2) @ (2, 3)` will work.
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [83]:
# this will not work
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: ignored

In [84]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4601, 0.4554],
        [0.6766, 0.3391]])

In [85]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.6650, 1.2599, 0.9889],
        [0.4904, 0.7949, 0.6394],
        [0.5532, 0.8877, 0.7153]])

In [86]:
# Element-wise multiplication
print(tensor, "*", tensor, end="")
print(f"= {tensor * tensor}")

tensor([2., 2., 2., 2., 2., 2., 2.]) * tensor([2., 2., 2., 2., 2., 2., 2.])= tensor([4., 4., 4., 4., 4., 4., 4.])


In [87]:
# Matrix multiplication
torch.matmul(tensor, tensor) # you dont need to transpose, tensor will take care of it

tensor(28.)

In [88]:
# Matrix multiplication by @
tensor @ tensor

tensor(28.)

In [89]:
tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

In [90]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

# Time Comparison

In [91]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(28.)
CPU times: user 1.31 ms, sys: 45 µs, total: 1.35 ms
Wall time: 1.36 ms


In [92]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 32 µs, sys: 5 µs, total: 37 µs
Wall time: 40.8 µs


tensor(28.)

### One of the most common errors in deep learning : **Shape Errors**

In [126]:
# Shapes of matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an aias for torch.matmul)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [127]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimesnions of a given tensor.

In [128]:
# transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [129]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [130]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape : {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape : torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregration)

In [131]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [132]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [133]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [134]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [135]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [136]:
%%time
torch.sum(x)

CPU times: user 294 µs, sys: 42 µs, total: 336 µs
Wall time: 282 µs


tensor(460)

In [137]:
%%time
x.sum()

CPU times: user 29 µs, sys: 5 µs, total: 34 µs
Wall time: 37.4 µs


tensor(460)

# Finding the positional min and max

In [138]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [139]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor which has the minimum value
x.argmin()

tensor(0)

In [140]:
x[0]

tensor(1)

In [141]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [142]:
x[9]

tensor(91)

In [143]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
  * Changing the shape of the view also changes that of the original input
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
(hstack) 
* Squeeze - removes all `1` dimensions from a tensor
* Unsquueze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way
  * Changing the shape of the premuted also changes that of the original input

In [144]:
# Let's create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [147]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshpaed, x_reshaped.shape

RuntimeError: ignored

In [148]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [149]:
# Add an extra dimension
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [150]:
testtensor = torch.arange(1., 11.)
testtensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [151]:
testtensor.reshape(5, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [152]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [154]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
# Changing z changes x (because a view of a tensor shares the same meomory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [156]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # vstack
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [157]:
x_stacked = torch.stack([x, x, x, x], dim=1) # hstack
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [158]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")


# Remove extra dimensions from x_reshpaed
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [159]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print("\nAt dim= 0")
print(f"New tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print("\nAt dim=1")
print(f"New tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

At dim= 0
New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])

At dim=1
New tensor : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape : torch.Size([9, 1])


In [160]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") # [color_channel, height, width]

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [161]:
x_original

tensor([[[8.6940e-01, 5.6772e-01, 7.4109e-01],
         [4.2940e-01, 8.8544e-01, 5.7390e-01],
         [2.6658e-01, 6.2745e-01, 2.6963e-01],
         ...,
         [8.8455e-01, 3.8850e-01, 3.9324e-01],
         [4.5545e-02, 4.2129e-01, 8.5366e-01],
         [5.6972e-01, 2.0877e-01, 6.5391e-01]],

        [[3.3968e-01, 9.5650e-01, 6.6023e-02],
         [3.4206e-01, 1.7213e-02, 3.0308e-01],
         [6.5762e-01, 9.8131e-01, 5.8397e-01],
         ...,
         [6.7008e-01, 6.1587e-02, 4.2213e-01],
         [4.8892e-01, 2.9742e-01, 6.8196e-01],
         [5.3223e-01, 8.5103e-01, 4.5559e-01]],

        [[1.8443e-01, 8.5328e-01, 5.6982e-01],
         [3.5680e-01, 1.7045e-01, 6.1719e-01],
         [2.3124e-02, 6.3169e-01, 7.4722e-01],
         ...,
         [5.4622e-01, 6.2962e-01, 4.5285e-01],
         [8.4301e-01, 2.0853e-01, 6.7919e-01],
         [4.9887e-01, 9.3264e-02, 3.0635e-01]],

        ...,

        [[7.5457e-01, 4.3883e-01, 1.7798e-01],
         [9.0903e-04, 2.9150e-01, 8.8188e-01]

In [162]:
x_original[0, 0, 0]

tensor(0.8694)

In [163]:
x_original[0, 0, 0] = 728218
# permute() also shares the same memory as the original input
# chaging the value of the original at a particular position
# also changes the value of the premuted at the particular postion
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [164]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3) # from 1 to 9 to 1x3x3
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [165]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [166]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [167]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [168]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [169]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [170]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [171]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [172]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [173]:
# Index on x to return 9
print(x[0, 2, 2]) #x[0][2][2]

# Indedx on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [174]:
x[0][2][2]

tensor(9)

## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has a functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [175]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warnings: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
# tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [176]:
array.dtype # defualt = float64

dtype('float64')

In [177]:
torch.arange(1.0, 8.0).dtype # default = float32

torch.float32

In [178]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [179]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [180]:
numpy_tensor.dtype

dtype('float32')

In [181]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Changing tensor and numpy does not change its converted numpy and tensor respectively.

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> againg -> agina ...`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [182]:
import torch 

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2933, 0.5889, 0.4117, 0.0992],
        [0.3078, 0.7786, 0.8016, 0.3649],
        [0.6286, 0.9663, 0.7687, 0.4566]])
tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [183]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # you have to call this again every time when you use rand
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility : 

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on teh GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrad as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [184]:
!nvidia-smi

Sat Apr 29 12:33:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [186]:
# Chcek for GPU access wit PyTorch 
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to set up device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [188]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [189]:
# Count number of devices 
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [190]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [191]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the CPU

In [192]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [193]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [194]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exerices & Extra-Curriculum

See exercies for this notebook here: 
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
